export declare const RolesEnum: {
    "784050272263471145": {
        STAFF: string;
        PROGRAMMING: string;
        GRAPHIC: string;
        ROBOTIC: string;
        SOUND: string;
        MANAGEMENT: string;
        BOT: string;
        SENIORITY: string;
        HEADLINE: string;
        INTERESTS: string;
        ETC: string;
        REGISTRED: string;
        BUMP: string;
        CHALLENGES: string;
        STARTER: string;
        JUNIOR: string;
        MIDDLE: string;
        SENIOR: string;
        SPECIALIST: string;
    };
    "": {
        STAFF: string;
        PROGRAMMING: string;
        GRAPHIC: string;
        ROBOTIC: string;
        SOUND: string;
        MANAGEMENT: string;
        BOT: string;
        SENIORITY: string;
        HEADLINE: string;
        INTERESTS: string;
        ETC: string;
        REGISTRED: string;
        BUMP: string;
        CHALLENGES: string;
        STARTER: string;
        JUNIOR: string;
        MIDDLE: string;
        SENIOR: string;
        SPECIALIST: string;
    };
};
